### ISSUE TITLE
Crashes in 6.5

### ISSUE THREAD

**Issue by xcasxcursex** [Belphemur/SoundSwitch#1095]
### What happened?

Crash. Soundswitch just exited, without any interaction, leaving an event log entry or two.
It's worked perfectly for years until now.

### Step to reproduce

Literally nothing. It's done this three times now, occurring while SoundSwitch is minimized to the tray, hidden, untouched, and no audio devices were changed. I don't even know it's happened until I stumble across the missing icon or the event log.

### Version

6.5

### What version of Windows are you seeing the problem on?

Windows 10

### Relevant log output

```sh
There's nothing in the soundswitch logs, it just exits.

Windows' Event Log has 

Application: SoundSwitch.exe
CoreCLR Version: 7.0.122.56804
.NET Version: 7.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at SoundSwitch.Audio.Manager.Interop.Com.User.User32+NativeMethods.GetWindowTextLength(HWND)
   at SoundSwitch.Audio.Manager.Interop.Com.User.User32+NativeMethods.GetWindowTextLength(HWND)
   at SoundSwitch.Audio.Manager.Interop.Com.User.User32.GetWindowText(HWND)
   at SoundSwitch.Audio.Manager.WindowMonitor+<>c__DisplayClass6_0.<ProcessWindowInformation>b__0()
   at SoundSwitch.Audio.Manager.Interop.Com.Threading.ComThread+<>c__DisplayClass9_0`1[[System.ValueTuple`3[[System.UInt32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<BeginInvoke>b__0()
   at System.Threading.Tasks.Task`1[[System.ValueTuple`3[[System.UInt32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at SoundSwitch.Audio.Manager.Interop.Com.Threading.ComTaskScheduler.<.ctor>b__2_0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

**Comment by Belphemur** [comment]
Hello,

Thanks for the Windows' event logs. I thought I was catching that error.
Gonna make a quick fix for this.

**Comment by Belphemur** [comment]
I think I got the issue, can you check with a Beta version ?
https://f000.backblazeb2.com/file/SoundSwitch/nightly/SoundSwitch-6.5.39816.6488.zip

Stop SoundSwitch and replace all the file where you installed it by what's in the Zip file and start SoundSwitch again.

**Comment by xcasxcursex** [comment]
> I think I got the issue, can you check with a Beta version ?

I am now running this test version, I will let you know if I have another crash. 
It takes some time between crashes, so for now, assume that everything is working :)

Thanks so much!
