### ISSUE TITLE
Keeps freezing

### ISSUE THREAD

**Issue by vertigo220** [Belphemur/SoundSwitch#1223]
### What happened?

I use this daily to switch between two audio devices, and almost every day, if not every day, it fails to work at least once. At first I thought it was just the keyboard shortcuts (hotkeys) not working, but when it just happened again, I tried clicking the icon to switch manually and it didn't show the device list popup. I right-clicked and it showed that menu, but when I hovered over the menu it just showed the mouse icon like it was busy, and I couldn't click anything. So it was unresponsive, and I'm thinking now that it's going unresponsive on a regular basis for some reason.

### Step to reproduce

Run the program and periodically use hotkeys to toggle between two audio devices.

### Version

6.7.2.0

### What version of Windows are you seeing the problem on?

Windows 10

### Relevant log output

```sh
?
```

**Comment by vertigo220** [comment]
So I'm not sure what's new, but this started roughly 2-3 weeks ago, and it's happening on a daily basis. I always have a couple dozen or so programs running in the tray, and every day the same two have issues, this and EarTrumpet, both audio device management apps. They've both been running for several months, if not a few years, without issue, until recently. The only thing I can think that might break them is switching in and out of a full-screen (windowed) game, but that's not new. Otherwise, the only thing that's changed that might be related is I switched from an old Nvidia GPU to a new(er) AMD one, and I did that around the same time these issues started, though I'm not certain which was first. But the more I think about it, the more convinced I am that must be the cause somehow.

As far as what's happening, both programs will just be unresponsive when I try to use them (and ALL other programs running in the tray will work fine). The only thing I can do at that point is to force kill them, but then when I try to relaunch them, even though the processes are running, they don't show back up in the tray for a while. Sometimes it takes a couple minutes, sometimes several.

**Comment by Belphemur** [comment]
Hey,

When you switch GPU, did you clean up the drivers ?
Tool to do that in safe mode :
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html

There are known issue when switching GPU brand and not cleaning completely the drivers.

**Comment by Belphemur** [comment]
These days, video card provide HDMI connectivity which also create an audio device ^^

Issue with driver can make that audio device misbehave and create problems for the user.

**Comment by vertigo220** [comment]
Yeah. It's actually DP but same thing. As I mentioned, I'm going to try swapping the card out, and I'm also planning on setting up a fresh install on another drive so I can figure out what the heck is going on. I'll report back once I have more info. But there's definitely a lot of things not right with this new card. That said, and I realize there's only so much that can be done, but I do wonder if perhaps even if it is an issue caused by the card/drivers (and it almost certainly is), that it's actually just exposing a problem in these programs. That is, perhaps there's an issue with the code that makes them break easily and it could be modified to make them more robust. Of course, the only way to know would be with logging, but AFAICT neither program has any. Is there any info I could provide that would allow you to see what exactly is happening and possibly be able to change it so it's more resilient in such circumstances?

**Comment by GoTVm** [comment]
This has been happening to me since I installed it around 6 months ago exactly like @vertigo220 described in the OP. The application gets stuck and the only way to make it work again is by terminating it via Task Manager and opening it back up. I tried updating it but that solved nothing.

I have not changed any audio/video card in my computer.

**Comment by Belphemur** [comment]
90% of the time, it's because of a driver issue in Windows. Not much I can do.
I've made everything I can to reduce chance of the app freezing when there are issue with the driver.

**Comment by GoTVm** [comment]
Any hint about what driver is causing this?

**Comment by Belphemur** [comment]
nvidia or AMD one usually.
I know both always suggest restarting after installing an update, and when the system just got updated it has a tendency of causing issue with the HDMI devices.

**Comment by vertigo220** [comment]
Just to update, as mentioned, this first started after switching GPUs. After I switched from one new AMD GPU to another, the issue went away, as did some others, so I think the GPU was defective somehow. But then, after switching back from that card to my old Nvidia GPU, which never had the issues before, I've since been having it again, only this time only with this program and not with EarTrumpet. And when switching from Nvidia to AMD and back I did the full DDU in safe mode with restarts, etc. So while it originally seemed to be an issue with the specific card, now that it's happening despite being back to the original state of things it seems very strange that it's happening again.

**Comment by mmomtchev** [comment]
On my machine, it does it a lot - it rarely runs more than a few hours without freezing. I suspect that it might be related to my VR headset which has audio devices.

I tried running it in `Visual Studio` and the last messages before a freeze are:

```
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Diagnostics.Process.dll
The thread '[Thread Destroyed]' (20332) has exited with code 0 (0x0).
```

I think that there is a call that throws causing the main thread to exit.

I will try to investigate further, but I am mostly a C++/UNIX engineer with next to zero experience with C#/UI code.

**Comment by GoTVm** [comment]
Mine was "fixed" in one of the updates; it freezes a lot less than it used to but still does sometimes
________________________________

**Comment by mmomtchev** [comment]
Ok, I added a `try` / `catch` here:
https://github.com/Belphemur/SoundSwitch/blob/5b572cca7e8d2f160b3566f15aa814a7c81ac392/SoundSwitch.Audio.Manager/WindowMonitor.cs#L86

And I got:
```
[00:56:22.738 ERR]]{SourceContext="SoundSwitch.Audio.Manager.WindowMonitor", ExceptionDetail={["HResult"]=-2147467259, ["Message"]="Access is denied.", ["Source"]="System.Diagnostics.Process", ["TargetSite"]="Void EnumProcessModulesUntilSuccess(Microsoft.Win32.SafeHandles.SafeProcessHandle, IntPtr[], Int32, Int32 ByRef, Int32)", ["NativeErrorCode"]=5, ["ErrorCode"]=-2147467259, ["Type"]="System.ComponentModel.Win32Exception"}} Couldn't start tray process.(at SoundSwitch.Audio.Manager.WindowMonitor+<>c__DisplayClass5_0.<.ctor>b__2)
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(SafeProcessHandle processHandle, IntPtr[] modules, Int32 size, Int32& needed, Int32 filterFlag)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at SoundSwitch.Audio.Manager.WindowMonitor.<>c__DisplayClass5_0.<.ctor>b__2() in C:\Users\mmom\src\SoundSwitch\SoundSwitch.Audio.Manager\WindowMonitor.cs:line 85
```

We will see if it still freezes

**Comment by mmomtchev** [comment]
Yeah, found something. Just launch `cmd.exe` as Administrator and switch to it. This will blow.

**Comment by Belphemur** [comment]
I think this has been fixed in 6.12.0
