### ISSUE TITLE
SoundSwitch Crash when Custom Notification is set and no Sound is chosen: System.FormatException Fatal Error

### ISSUE THREAD

**Issue by Galtsu** [Belphemur/SoundSwitch#175]
Hello!

Just wanted to inform you there is a problem with notification option "Customized Sound Notification"
If you choose it, but close the window without selecting a sound file the program crashes and logs read out:
```

TracerX: Log file opened at 25.3.2017 1.37.34.  FullFilePolicy = Wrap, Use_00 = False, MaxGrowth = 1 MB, AppendIfSmallerThan = 0 1, initial size = 3.
01.37.40.794 Fatal <null> SoundSwitch+ Exception Occurred Exception type: System.FormatException
Message: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
Source: mscorlib
StackTrace:
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at SoundSwitch.Framework.NotificationManager.NotificationManager.SetNotification(NotificationTypeEnum notificationTypeEnum) in D:\VS\SoundSwitch\SoundSwitch\Framework\NotificationManager\NotificationManager.cs:line 77
   at SoundSwitch.Framework.NotificationManager.NotificationManager.Init() in D:\VS\SoundSwitch\SoundSwitch\Framework\NotificationManager\NotificationManager.cs:line 44
   at SoundSwitch.Model.AppModel.InitializeMain() in D:\VS\SoundSwitch\SoundSwitch\Model\AppModel.cs:line 216
   at SoundSwitch.Program.Main() in D:\VS\SoundSwitch\SoundSwitch\Program.cs:line 128

This can be easily fixed by changing "NotificationSettings":3 -> 0 or 1 in SoundSwitchConfiguration.json @%appdata%\Roaming\SoundSwitch
```

System Specs:
OS: Windows 10 x64
RAM: 16GB DDR4
Motherboard: ASUS Prime X370-PRO AM4
CPU: AMD AM4 1800X
GPU: Gigabyte G1 Gaming RX480 8GB
System Disk: Corsair MP500

**Comment by FireEmerald** [comment]
Confirmed at fdff85531e7838a803a5d0bd67a7ffd388bef08e.
Aaaaaand the application **keeps crashing** until modifying the config file manually...
