### ISSUE TITLE
Crashes at startup when all playback devices are disabled

### ISSUE THREAD

**Issue by moomons** [Belphemur/SoundSwitch#427]
Easy repro:
Simply disable ALL playback devices in Sound control panel (mmsys.cpl) then start SoundSwitch (5.0.3).

I removed `%appdata%\SoundSwitch` entirely and it still crashes, so the config file doesn't matter .

```
[18:42:49.718 FTL] Exception Occurred  (at SoundSwitch.Program.HandleException)
System.Runtime.Remoting.RemotingException: The channel 'SoundSwitch' is not registered with remoting services.
   at System.Runtime.Remoting.Channels.ChannelServices.UnregisterChannel(IChannel chnl)
   at SoundSwitch.Program.Main() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Program.cs:line 167
```

[soundswitch20200503_crash.log](https://github.com/Belphemur/SoundSwitch/files/4572488/soundswitch20200503_crash.log)

**Comment by moomons** [comment]
Looks like it crashed in ChangeIcon because the exception is not handled when there are no AudioEndpoint.

![Annotation 2020-05-03 190523](https://user-images.githubusercontent.com/10822203/80931805-0ef54f80-8d71-11ea-86a8-c4a5633ce33e.png)

**Comment by moomons** [comment]
Posted PR #428 for an easy fix.

btw I noticed two more crashes during the debugging of this issue:

1. In the same log file above, the log packing thread throws the following exception:
```
[18:42:52.770 FTL] Exception Occurred  (at SoundSwitch.Program.HandleException)
System.IO.IOException: The process cannot access the file 'C:\Users\u\AppData\Roaming\SoundSwitch\Logs\soundswitch20200503.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at SoundSwitch.Program.HandleException(Exception exception) in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Program.cs:line 245
   at SoundSwitch.Program.Main() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Program.cs:line 172
```
I guess the app has to close the log before the other thread can pack it.

2. After the app launched normally, if the last enabled playback device it disabled, the app will crash:
![disabling the only playback device](https://user-images.githubusercontent.com/10822203/80932822-03f0ee00-8d76-11ea-8165-3d55a8383ac5.png)
Solution: `MMNotificationClient.OnDefaultDeviceChanged` also needs some corner case handling logic.
