### ISSUE TITLE
crash report: System.Threading.ThreadStateException: Instance isn't set even after waiting 1250 ms

### ISSUE THREAD

**Issue by cdrandin** [Belphemur/SoundSwitch#493]
**What were you doing when it crashed ?**
Turned on computer and crashed appear immediately.

**To Reproduce**
Above

**ZIP**
[SoundSwitch-crashlog-14_8_2020.zip](https://github.com/Belphemur/SoundSwitch/files/5076032/SoundSwitch-crashlog-14_8_2020.zip)

**Comment by Belphemur** [comment]
I'm trying to reproduce your issue, for now without success

**Comment by FireEmerald** [comment]
Got the same error after the update to SoundSwitch 5.5.1 right on startup of application.
```
[10:03:34.912 INF] Refreshed device of state Active, Unplugged (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister+<Refresh>d__12.MoveNext)
[10:04:11.022 FTL] Exception Occurred  (at SoundSwitch.Program.HandleException)
System.Threading.ThreadStateException: Instance isn't set even after waiting 1250 ms
   at SoundSwitch.Framework.WinApi.WindowsAPIAdapter.WaitForHandle() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Framework\WinApi\WindowsAPIAdapter.cs:line 224
   at SoundSwitch.Framework.WinApi.WindowsAPIAdapter.RegisterHotKey(HotKey hotKey) in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Framework\WinApi\WindowsAPIAdapter.cs:line 160
   at SoundSwitch.Model.AppModel.RegisterHotKey(HotKey hotkeys) in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Model\AppModel.cs:line 396
   at SoundSwitch.Model.AppModel.InitializeMain() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Model\AppModel.cs:line 212
   at SoundSwitch.Program.InitAsync(TrayIcon icon) in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Program.cs:line 160
   at SoundSwitch.Program.<>c.<<Main>b__1_2>d.MoveNext() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Program.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
```
![crash](https://user-images.githubusercontent.com/1107939/90733558-0186b580-e2cd-11ea-94fe-cc35bd8e1183.png)

This window popped up multiple times and i always clicked on Ja (Yes). After that the generated `SoundSwitch-crashlog-20_8_2020.zip` file was generated, but malformed. Trying to zip the %AppData%\SoundSwitch failed due to the fact that a process locked the latest *.log file (soundswitch20200820_001.log).

**Comment by Belphemur** [comment]
@FireEmerald Directly related to #495 

I think it's related to the new instance of SoundSwitch trying to close the old one.

I'm thinking of removing that feature.
