### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Otiel** [Belphemur/SoundSwitch#626]
**Describe the bug**
The following MessageBox was displayed:
```
It seems SoundSwitch has crashed.

Collection was modified; enumeration operation may not execute.
```

Log content:
```
[16:31:52.076 INF] [Active] Refreshed all devices. 1/rec, 3/play (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[16:31:52.239 INF] [Active, Unplugged] Refreshed all devices. 3/rec, 7/play (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:42.684 INF] [Active, Unplugged] Refreshing all devices (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:42.684 INF] [Active] Refreshing all devices (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:43.002 INF] [Active] Refreshed all devices. 1/rec, 3/play (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:43.002 INF] [Active] Refreshing all devices (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:43.137 INF] [Active, Unplugged] Refreshed all devices. 3/rec, 6/play (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:43.137 INF] [Active, Unplugged] Refreshing all devices (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:43.334 INF] [Active] Refreshed all devices. 1/rec, 4/play (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:38:43.565 INF] [Active, Unplugged] Refreshed all devices. 3/rec, 7/play (at SoundSwitch.Framework.Audio.Lister.CachedAudioDeviceLister.Refresh)
[19:40:13.938 FTL] Exception Occurred  (at SoundSwitch.Program.HandleException)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at SoundSwitch.Framework.TrayIcon.TooltipInfoManager.TootipInfo.TooltipInfoPlayback.TextToDisplay() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Framework\TrayIcon\TooltipInfoManager\TootipInfo\TooltipInfoPlayback.cs:line 34
   at SoundSwitch.Framework.TrayIcon.TooltipInfoManager.TootipInfo.TooltipInfoBoth.TextToDisplay() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Framework\TrayIcon\TooltipInfoManager\TootipInfo\TooltipInfoBoth.cs:line 36
   at SoundSwitch.Framework.TrayIcon.TooltipInfoManager.TooltipInfoManager.ShowTooltipInfo() in C:\Users\Antoine\source\repos\SoundSwitch\SoundSwitch\Framework\TrayIcon\TooltipInfoManager\TooltipInfoManager.cs:line 89
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Version**
SoundSwitch v5.9.0

**To Reproduce**
Not sure, came back to my PC after several hours and the MessageBox was displayed.

[SoundSwitch-crashlog-4_5_2021.zip](https://github.com/Belphemur/SoundSwitch/files/6423633/SoundSwitch-crashlog-4_5_2021.zip)

**Comment by Belphemur** [comment]
It's a race condition, clicking on the dropdown while it's refreshing the devices ...
I'll see what I can do.
